name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Check for Azure token
        run: |
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
            echo "⚠️ AZURE_STATIC_WEB_APPS_API_TOKEN not set"
            echo "📋 To fix this:"
            echo "1. Go to: https://github.com/Artecx-Solutions/Shorten-URLs-Frontend/settings/secrets/actions"
            echo "2. Click 'New repository secret'"
            echo "3. Name: AZURE_STATIC_WEB_APPS_API_TOKEN"
            echo "4. Value: [Get this from Azure Static Web Apps → Manage deployment token]"
            echo "5. Click 'Add secret'"
            echo ""
            echo "🔄 For now, skipping Azure deployment and just building the app..."
            echo "✅ Build completed successfully - ready for Azure deployment once token is added"
          else
            echo "✅ Azure token found, proceeding with deployment"
          fi
      - name: Build And Deploy
        id: builddeploy
        if: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN != '' }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"
          skip_app_build: false
          production_branch: main
      - name: Skip Azure deployment
        if: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN == '' }}
        run: |
          echo "⏭️ Skipping Azure deployment - token not configured"
          echo "✅ Build completed successfully!"
          echo "📦 Built files are ready in the 'dist' folder"
          echo "🔧 Add Azure token to enable automatic deployment"
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        if: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN != '' }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
      - name: Skip close pull request
        if: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN == '' }}
        run: echo "⏭️ Skipping Azure pull request close - token not configured"
